# Generated by Django 2.1.1 on 2018-09-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180901_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Content',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
